php:
  build: .
  ports:
   - "80:80"
   - "443:443"
  volumes:
   - ./agenda:/var/www/html
  links:
   - localhost
localhost:
  image: mysql:5.7
  ports:
    - '3306:3306'
  volumes:
   - /var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=usbw
   - MYSQL_DATABASE=projeto_final